<a href="https://colab.research.google.com/github/LoopyMekanic/Analysis/blob/Trying-to-learn/Pandas_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Pandas and Numpy
import pandas as pd
import numpy as np

In [3]:
# Create Pandas Series from list (column in table)
my_list = [5,9,12,27]
# Create a series
my_series = pd.Series(my_list)

In [4]:
# Print without formatting
print(my_series)

0     5
1     9
2    12
3    27
dtype: int64

In [5]:
# Print with formatting
my_series

0     5
1     9
2    12
3    27
dtype: int64

In [6]:
# Pull item from series with index number
print(my_series[1])
my_series[1]

9

np.int64(9)

In [8]:
# Create labels with index arguementny__index = ["A", "B", "C", "D"]
my_index = ["A", "B", "C", "D"]
my_series2 = pd.Series(my_list, my_index)
my_series2

A     5
B     9
C    12
D    27
dtype: int64

In [9]:
# Create labels manually
my_series3 = pd.Series(my_list, ["E", "F", "G", "H"])
my_series3

E     5
F     9
G    12
H    27
dtype: int64

In [12]:
# Pull item from series with label
# print(my_series3.iloc[3])
print(my_series3["G"])

12