<a href="https://colab.research.google.com/github/LoopyMekanic/Analysis/blob/Trying-to-learn/Pandas_4_Pulling_Data_From_Data_Frame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
# Import CSV file /c/mydata
my_df = pd.read_csv('/content/dog_data.csv')

In [4]:
my_df

                    Breed              Color        DogName  OwnerZip
0                COCKAPOO              BROWN        CHARLEY     15236
1            GER SHEPHERD        BLACK/BROWN         TACODA     15238
2           BELG MALINOIS            BRINDLE           EICH     15238
3                   MIXED        BLACK/BROWN          ARROW     15104
4     AM PIT BULL TERRIER        WHITE/BROWN         OAKLEY     15139
...                   ...                ...            ...       ...
2665         GOLDENDOODLE              BROWN        WINSLOW     15044
2666    YORKSHIRE TERRIER        BLACK/BROWN  ROCKY KALAKOS     15220
2667              LAB MIX  WHITE/BLACK/BROWN          ELLIE     15220
2668         GOLDENDOODLE              WHITE       CLARENCE     15143
2669    SHETLAND SHEEPDOG              BLACK        GRIFFIN     15136

[2670 rows x 4 columns]

In [5]:
# Get columns using bracket notation (return panda series)
my_df['DogName']

0             CHARLEY
1              TACODA
2                EICH
3               ARROW
4              OAKLEY
            ...
2665          WINSLOW
2666    ROCKY KALAKOS
2667            ELLIE
2668         CLARENCE
2669          GRIFFIN
Name: DogName, Length: 2670, dtype: object

In [6]:
# Get columns using dot notation
my_df.Color

0                   BROWN
1             BLACK/BROWN
2                 BRINDLE
3             BLACK/BROWN
4             WHITE/BROWN
              ...
2665                BROWN
2666          BLACK/BROWN
2667    WHITE/BLACK/BROWN
2668                WHITE
2669                BLACK
Name: Color, Length: 2670, dtype: object

In [7]:
# Select specific column using location
my_df.iloc[:,0]

0                  COCKAPOO
1              GER SHEPHERD
2             BELG MALINOIS
3                     MIXED
4       AM PIT BULL TERRIER
               ...
2665           GOLDENDOODLE
2666      YORKSHIRE TERRIER
2667                LAB MIX
2668           GOLDENDOODLE
2669      SHETLAND SHEEPDOG
Name: Breed, Length: 2670, dtype: object

In [10]:
# Select more specific column using location
# my_df.iloc[0:3,1]
my_df.iloc[42:900,1]

42             BROWN
43           SPOTTED
44       WHITE/BROWN
45     BLACK/BRINDLE
46             WHITE
           ...
895            MULTI
896      BLACK/BROWN
897            BLACK
898        RED/BROWN
899        BLACK/TAN
Name: Color, Length: 858, dtype: object

In [11]:
# Get information about dataframe
my_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2670 entries, 0 to 2669
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Breed     2670 non-null   object
 1   Color     2665 non-null   object
 2   DogName   2669 non-null   object
 3   OwnerZip  2670 non-null   int64
dtypes: int64(1), object(3)
memory usage: 83.6+ KB

In [12]:
# Get shape of rows and columns
my_df.shape

(2670, 4)

In [13]:
# Get number of dimensions
my_df.ndim

2

In [14]:
# Get column datatypes
my_df.dtypes

Breed       object
Color       object
DogName     object
OwnerZip     int64
dtype: object

In [15]:
# Get some statistics about the data
my_df.describe()

           OwnerZip
count   2670.000000
mean   15268.109738
std     2747.560641
min    15003.000000
25%    15102.000000
50%    15136.000000
75%    15227.000000
max    97206.000000

In [16]:
# Describe a specific column - Breed
my_df["Breed"].describe()

count      2670
unique      185
top       MIXED
freq        235
Name: Breed, dtype: object

In [17]:
# Describe a specific column - Color
my_df["Color"].describe()

count      2665
unique       72
top       BLACK
freq        371
Name: Color, dtype: object

In [18]:
# Describe a specific column - DogName
my_df["DogName"].describe()

count     2669
unique    1428
top       LUCY
freq        35
Name: DogName, dtype: object

In [20]:
# Count data in dataframe - Count distinct values - Descending
my_df["Color"].value_counts()

Color
BLACK                   371
BROWN                   309
WHITE                   226
WHITE/BLACK             196
BLACK/BROWN             183
                       ...
BROWN/ORANGE              1
BLACK/ORANGE/BRINDLE      1
BROWN/FAWN                1
BLACK/BROWN/GREY          1
BROWN/LIVER               1
Name: count, Length: 72, dtype: int64

In [21]:
# Count distinct values - Ascending
my_df["Color"].value_counts(ascending=True)

Color
BROWN/ORANGE              1
BLACK/ORANGE/BRINDLE      1
BROWN/LIVER               1
BLACK/BROWN/GREY          1
BROWN/FAWN                1
                       ...
BLACK/BROWN             183
WHITE/BLACK             196
WHITE                   226
BROWN                   309
BLACK                   371
Name: count, Length: 72, dtype: int64

In [22]:
# Dog Names - without NaN
my_df['DogName'].value_counts()

DogName
LUCY          35
BELLA         30
BUDDY         29
BAILEY        29
DAISY         26
              ..
LULU DERRY     1
HEMINGWAY      1
LUCY LOU       1
JENA LYNN      1
BLITZ          1
Name: count, Length: 1428, dtype: int64

In [23]:
# Dog Names - with NaN
my_df['DogName'].value_counts(dropna=False)

DogName
LUCY      35
BELLA     30
BUDDY     29
BAILEY    29
DAISY     26
          ..
ANDI       1
CHEVY      1
FINLEY     1
ASHE       1
DISNEY     1
Name: count, Length: 1429, dtype: int64

In [24]:
# Get relative frequency - Percentage
my_df["Color"].value_counts(normalize=True)

Color
BLACK                   0.139212
BROWN                   0.115947
WHITE                   0.084803
WHITE/BLACK             0.073546
BLACK/BROWN             0.068668
                          ...
BROWN/ORANGE            0.000375
BLACK/ORANGE/BRINDLE    0.000375
BROWN/FAWN              0.000375
BLACK/BROWN/GREY        0.000375
BROWN/LIVER             0.000375
Name: proportion, Length: 72, dtype: float64

In [28]:
# Get specific item count (get all white dogs)
# my_df["Color"].value_counts()["WHITE"]
print(my_df["Color"].value_counts()["WHITE"])

226

In [29]:
# Count unique values - Size
my_df.groupby('Color').size()

Color
APRICOT              15
BEIGE                 5
BLACK               371
BLACK WITH WHITE     21
BLACK/BRINDLE         5
                   ...
WHITE/ORANGE          5
WHITE/RED            14
WHITE/TAN            50
WHITE/YELLOW          2
YELLOW               51
Length: 72, dtype: int64

In [30]:
# Count unique values - Count
my_df.groupby('Color').count()

                  Breed  DogName  OwnerZip
Color
APRICOT              15       15        15
BEIGE                 5        5         5
BLACK               371      371       371
BLACK WITH WHITE     21       21        21
BLACK/BRINDLE         5        5         5
...                 ...      ...       ...
WHITE/ORANGE          5        5         5
WHITE/RED            14       14        14
WHITE/TAN            50       50        50
WHITE/YELLOW          2        2         2
YELLOW               51       51        51

[72 rows x 3 columns]