<a href="https://colab.research.google.com/github/LoopyMekanic/Analysis/blob/Trying-to-learn/Pandas_Adding_and_Removing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np
# Import CSV File
my_df = pd.read_csv('/content/dog2.txt')

In [21]:
my_df

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2        BELG MALINOIS      BRINDLE     EICH     15238
3                MIXED  BLACK/BROWN    ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

In [22]:
# Add column from List (must match)
gender_list = ["Male", "Female", "Male", "Male", "Female"]
# Create a column and assign the stuff
my_df["Gender"] = gender_list
my_df

                 Breed        Color  DogName  OwnerZip  Gender
0             COCKAPOO        BROWN  CHARLEY     15236    Male
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238  Female
2        BELG MALINOIS      BRINDLE     EICH     15238    Male
3                MIXED  BLACK/BROWN    ARROW     15104    Male
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139  Female

In [23]:
# Add default values
my_df["Alive/Dead"] = [True]*len(my_df)
my_df

                 Breed        Color  DogName  OwnerZip  Gender  Alive/Dead
0             COCKAPOO        BROWN  CHARLEY     15236    Male        True
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238  Female        True
2        BELG MALINOIS      BRINDLE     EICH     15238    Male        True
3                MIXED  BLACK/BROWN    ARROW     15104    Male        True
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139  Female        True

In [24]:
# Add null values NaN
my_df["ShowDogs"] = [np.nan]*len(my_df)
my_df

,Breed,Color,DogName,OwnerZip,Gender,Alive/Dead,ShowDogs
0,COCKAPOO,BROWN,CHARLEY,15236,Male,True,NaN
1,GER SHEPHERD,BLACK/BROWN,TACODA,15238,Female,True,NaN
2,BELG MALINOIS,BRINDLE,EICH,15238,Male,True,NaN
3,MIXED,BLACK/BROWN,ARROW,15104,Male,True,NaN
4,AM PIT BULL TERRIER,WHITE/BROWN,OAKLEY,15139,Female,True,NaN

In [25]:
# Add column with .insert() (allows you to specify where)
my_df.insert(1,"Adopted", [True]*len(my_df), True)
my_df

,Breed,Adopted,Color,DogName,OwnerZip,Gender,Alive/Dead,ShowDogs
0,COCKAPOO,True,BROWN,CHARLEY,15236,Male,True,NaN
1,GER SHEPHERD,True,BLACK/BROWN,TACODA,15238,Female,True,NaN
2,BELG MALINOIS,True,BRINDLE,EICH,15238,Male,True,NaN
3,MIXED,True,BLACK/BROWN,ARROW,15104,Male,True,NaN
4,AM PIT BULL TERRIER,True,WHITE/BROWN,OAKLEY,15139,Female,True,NaN

In [26]:
# Add column with .assign() (creates a new DataFrame)
my_df2 = my_df.assign(Horse=[False]*len(my_df))
my_df2

,Breed,Adopted,Color,DogName,OwnerZip,Gender,Alive/Dead,ShowDogs,Horse
0,COCKAPOO,True,BROWN,CHARLEY,15236,Male,True,NaN,False
1,GER SHEPHERD,True,BLACK/BROWN,TACODA,15238,Female,True,NaN,False
2,BELG MALINOIS,True,BRINDLE,EICH,15238,Male,True,NaN,False
3,MIXED,True,BLACK/BROWN,ARROW,15104,Male,True,NaN,False
4,AM PIT BULL TERRIER,True,WHITE/BROWN,OAKLEY,15139,Female,True,NaN,False

In [27]:
# Remove column
my_df.drop("ShowDogs", axis=1, inplace=True)

In [28]:
# Axis is column heading or row headings (0=rows, 1=columns)
my_df

,Breed,Adopted,Color,DogName,OwnerZip,Gender,Alive/Dead
0,COCKAPOO,True,BROWN,CHARLEY,15236,Male,True
1,GER SHEPHERD,True,BLACK/BROWN,TACODA,15238,Female,True
2,BELG MALINOIS,True,BRINDLE,EICH,15238,Male,True
3,MIXED,True,BLACK/BROWN,ARROW,15104,Male,True
4,AM PIT BULL TERRIER,True,WHITE/BROWN,OAKLEY,15139,Female,True

In [29]:
# Run again my_df and gender is back....inplace=False default

In [30]:
# Run one more time just to see...

In [31]:
# Remove rows
my_df.drop(3, axis=0, inplace=False)

,Breed,Adopted,Color,DogName,OwnerZip,Gender,Alive/Dead
0,COCKAPOO,True,BROWN,CHARLEY,15236,Male,True
1,GER SHEPHERD,True,BLACK/BROWN,TACODA,15238,Female,True
2,BELG MALINOIS,True,BRINDLE,EICH,15238,Male,True
4,AM PIT BULL TERRIER,True,WHITE/BROWN,OAKLEY,15139,Female,True