<a href="https://colab.research.google.com/github/LoopyMekanic/Analysis/blob/Trying-to-learn/Pandas_4_Pulling_Data_from_Data_Frame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np

In [16]:
# Import CSV File /c/mydata
my_df = pd.read_csv('/content/dog_data.csv')

In [17]:
my_df

                    Breed              Color        DogName  OwnerZip
0                COCKAPOO              BROWN        CHARLEY     15236
1            GER SHEPHERD        BLACK/BROWN         TACODA     15238
2           BELG MALINOIS            BRINDLE           EICH     15238
3                   MIXED        BLACK/BROWN          ARROW     15104
4     AM PIT BULL TERRIER        WHITE/BROWN         OAKLEY     15139
...                   ...                ...            ...       ...
2665         GOLDENDOODLE              BROWN        WINSLOW     15044
2666    YORKSHIRE TERRIER        BLACK/BROWN  ROCKY KALAKOS     15220
2667              LAB MIX  WHITE/BLACK/BROWN          ELLIE     15220
2668         GOLDENDOODLE              WHITE       CLARENCE     15143
2669    SHETLAND SHEEPDOG              BLACK        GRIFFIN     15136

[2670 rows x 4 columns]

In [18]:
# Pull out a row
my_df.loc[0]

Breed       COCKAPOO
Color          BROWN
DogName      CHARLEY
OwnerZip       15236
Name: 0, dtype: object

In [19]:
# Pull out multiple rows 0 and 5
my_df.loc[[0,2,4]]

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
2        BELG MALINOIS      BRINDLE     EICH     15238
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

In [20]:
# Grab first 5 rows
my_df.head()

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2        BELG MALINOIS      BRINDLE     EICH     15238
3                MIXED  BLACK/BROWN    ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

In [21]:
# Grab certain number of first rows
my_df.head(9)

                 Breed        Color            DogName  OwnerZip
0             COCKAPOO        BROWN            CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN             TACODA     15238
2        BELG MALINOIS      BRINDLE               EICH     15238
3                MIXED  BLACK/BROWN              ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN             OAKLEY     15139
5     SCOTTISH TERRIER        BLACK             BAILEY     15129
6    YORKSHIRE TERRIER    BLACK/TAN  MIMI PEARL FOSTER     15090
7        DACHSHUND MIX  WHITE/BROWN              LEROI     15101
8    SHETLAND SHEEPDOG  WHITE/BROWN         ZOE VITSAS     15238

In [22]:
# Grab the last 5 rows
my_df.tail()

                  Breed              Color        DogName  OwnerZip
2665       GOLDENDOODLE              BROWN        WINSLOW     15044
2666  YORKSHIRE TERRIER        BLACK/BROWN  ROCKY KALAKOS     15220
2667            LAB MIX  WHITE/BLACK/BROWN          ELLIE     15220
2668       GOLDENDOODLE              WHITE       CLARENCE     15143
2669  SHETLAND SHEEPDOG              BLACK        GRIFFIN     15136

In [23]:
# Grab a certain number of last rows
my_df.tail(10)

                   Breed              Color        DogName  OwnerZip
2660              PUGGLE              BROWN           MACY     15044
2661     ENGLISH MASTIFF               FAWN          MARGE     15143
2662          WEIMARANER               GREY          BELLA     15102
2663  LABRADOR RETRIEVER              BROWN           NINO     15102
2664  COCKER SPANIEL MIX        WHITE/BLACK           JACK     15102
2665        GOLDENDOODLE              BROWN        WINSLOW     15044
2666   YORKSHIRE TERRIER        BLACK/BROWN  ROCKY KALAKOS     15220
2667             LAB MIX  WHITE/BLACK/BROWN          ELLIE     15220
2668        GOLDENDOODLE              WHITE       CLARENCE     15143
2669   SHETLAND SHEEPDOG              BLACK        GRIFFIN     15136