<a href="https://colab.research.google.com/github/LoopyMekanic/Analysis/blob/Trying-to-learn/Pandas_6_Conditionals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
# Import CSV File
my_df = pd.read_csv('/content/dog_data.csv')

In [4]:
my_df

                    Breed              Color        DogName  OwnerZip
0                COCKAPOO              BROWN        CHARLEY     15236
1            GER SHEPHERD        BLACK/BROWN         TACODA     15238
2           BELG MALINOIS            BRINDLE           EICH     15238
3                   MIXED        BLACK/BROWN          ARROW     15104
4     AM PIT BULL TERRIER        WHITE/BROWN         OAKLEY     15139
...                   ...                ...            ...       ...
2665         GOLDENDOODLE              BROWN        WINSLOW     15044
2666    YORKSHIRE TERRIER        BLACK/BROWN  ROCKY KALAKOS     15220
2667              LAB MIX  WHITE/BLACK/BROWN          ELLIE     15220
2668         GOLDENDOODLE              WHITE       CLARENCE     15143
2669    SHETLAND SHEEPDOG              BLACK        GRIFFIN     15136

[2670 rows x 4 columns]

In [5]:
# Conditional Selection < = > <= >= == etc
my_df == "Brown" # Returns a Boolean T/F

      Breed  Color  DogName  OwnerZip
0     False  False    False     False
1     False  False    False     False
2     False  False    False     False
3     False  False    False     False
4     False  False    False     False
...     ...    ...      ...       ...
2665  False  False    False     False
2666  False  False    False     False
2667  False  False    False     False
2668  False  False    False     False
2669  False  False    False     False

[2670 rows x 4 columns]

In [6]:
# Return actual data by passing that into dataframe
my_df[my_df == "BROWN"]

     Breed  Color DogName  OwnerZip
0      NaN  BROWN     NaN       NaN
1      NaN    NaN     NaN       NaN
2      NaN    NaN     NaN       NaN
3      NaN    NaN     NaN       NaN
4      NaN    NaN     NaN       NaN
...    ...    ...     ...       ...
2665   NaN  BROWN     NaN       NaN
2666   NaN    NaN     NaN       NaN
2667   NaN    NaN     NaN       NaN
2668   NaN    NaN     NaN       NaN
2669   NaN    NaN     NaN       NaN

[2670 rows x 4 columns]

In [ ]:
# Just return the color column
my_df[my_df == "BROWN"]["Color"]

In [7]:
# Return multiple columns
my_df[my_df == "BROWN"][["Color", "DogName"]]

      Color DogName
0     BROWN     NaN
1       NaN     NaN
2       NaN     NaN
3       NaN     NaN
4       NaN     NaN
...     ...     ...
2665  BROWN     NaN
2666    NaN     NaN
2667    NaN     NaN
2668    NaN     NaN
2669    NaN     NaN

[2670 rows x 2 columns]

In [8]:
# Return a dataframe of the specified info
my_df[my_df['Color'] == "BROWN"]

                   Breed  Color           DogName  OwnerZip
0               COCKAPOO  BROWN           CHARLEY     15236
12      AM PITT BULL MIX  BROWN              KING     15235
25            BEAGLE MIX  BROWN  CHRISTINA "TINA"     15025
38            BEAGLE MIX  BROWN        HONEY PUCK     15241
39             CHIHUAHUA  BROWN              ROXY     15147
...                  ...    ...               ...       ...
2652  LABRADOR RETRIEVER  BROWN            WESTIN     15237
2657        GER SHEPHERD  BROWN             SARAH     15239
2660              PUGGLE  BROWN              MACY     15044
2663  LABRADOR RETRIEVER  BROWN              NINO     15102
2665        GOLDENDOODLE  BROWN           WINSLOW     15044

[309 rows x 4 columns]

In [9]:
# Multiple conditional AND
# my_df[my_df['Color'] == "BROWN"]
my_df[(my_df['Color'] == "BROWN") & (my_df["Breed"] == "MIXED")]

      Breed  Color        DogName  OwnerZip
42    MIXED  BROWN         STELLA     15044
272   MIXED  BROWN           HANK     15220
371   MIXED  BROWN          TEDDY     15136
402   MIXED  BROWN      GEORGIOUS     15212
505   MIXED  BROWN        HERSHEY     15071
523   MIXED  BROWN  MINDY MAZUREK     15037
572   MIXED  BROWN          STEVE     15229
584   MIXED  BROWN           BEAR     15122
602   MIXED  BROWN          CHLOE     15106
818   MIXED  BROWN         PEANUT     15025
943   MIXED  BROWN        DEE DEE     15031
946   MIXED  BROWN           SAGE     15035
948   MIXED  BROWN          BELLA     15035
995   MIXED  BROWN         MISTER     15139
1006  MIXED  BROWN        VANESSA     15065
1042  MIXED  BROWN           JACK     15223
1123  MIXED  BROWN         BUDDIE     15122
1195  MIXED  BROWN         COOPER     15071
1204  MIXED  BROWN            POE     15044
1211  MIXED  BROWN          EPPEY     15218
1258  MIXED  BROWN           BLUE     15235
1322  MIXED  BROWN         PHOEBE     15025
1466  MIXED  BROWN          JAXIE     15229
1476  MIXED  BROWN          PIPPA     15122
1659  MIXED  BROWN         ISABEL     15044
1780  MIXED  BROWN         WILBUR     15202
1798  MIXED  BROWN           PINO     15139
1847  MIXED  BROWN         MICKEY     15227
2180  MIXED  BROWN           KONA     15102
2351  MIXED  BROWN          BELLA     15209
2393  MIXED  BROWN         PEANUT     15143
2403  MIXED  BROWN           TOBY     15237
2430  MIXED  BROWN           LUCY     15229
2441  MIXED  BROWN          CASEY     15120
2524  MIXED  BROWN         PEANUT     15227
2562  MIXED  BROWN           JEFF     15146
2581  MIXED  BROWN           BRAX     15143
2597  MIXED  BROWN         BAILEY     15065

In [10]:
# Get the length of that
len(my_df[(my_df['Color'] == "BROWN") & (my_df["Breed"] == "MIXED")])

38

In [11]:
# Multiple conditional OR
my_df[(my_df['Color'] == "BROWN") | (my_df["Breed"] == "MIXED")]

                   Breed        Color           DogName  OwnerZip
0               COCKAPOO        BROWN           CHARLEY     15236
3                  MIXED  BLACK/BROWN             ARROW     15104
12      AM PITT BULL MIX        BROWN              KING     15235
15                 MIXED        WHITE             RUSTY     15120
25            BEAGLE MIX        BROWN  CHRISTINA "TINA"     15025
...                  ...          ...               ...       ...
2657        GER SHEPHERD        BROWN             SARAH     15239
2658               MIXED        WHITE              LUNA     15017
2660              PUGGLE        BROWN              MACY     15044
2663  LABRADOR RETRIEVER        BROWN              NINO     15102
2665        GOLDENDOODLE        BROWN           WINSLOW     15044

[506 rows x 4 columns]

In [12]:
# Length of that
len(my_df[(my_df['Color'] == "BROWN") | (my_df["Breed"] == "MIXED")])

506

In [14]:
# Pull a specific thing from that
my_df[(my_df['Color'] == "BROWN") & (my_df["Breed"] == "MIXED")]["DogName"]

42             STELLA
272              HANK
371             TEDDY
402         GEORGIOUS
505           HERSHEY
523     MINDY MAZUREK
572             STEVE
584              BEAR
602             CHLOE
818            PEANUT
943           DEE DEE
946              SAGE
948             BELLA
995            MISTER
1006          VANESSA
1042             JACK
1123           BUDDIE
1195           COOPER
1204              POE
1211            EPPEY
1258             BLUE
1322           PHOEBE
1466            JAXIE
1476            PIPPA
1659           ISABEL
1780           WILBUR
1798             PINO
1847           MICKEY
2180             KONA
2351            BELLA
2393           PEANUT
2403             TOBY
2430             LUCY
2441            CASEY
2524           PEANUT
2562             JEFF
2581             BRAX
2597           BAILEY
Name: DogName, dtype: object